var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/manager-hr/persetujuan-izin-cuti/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5c730f1e._.js")
R.c("server/chunks/ssr/HRIS-WEB_4ee5820b._.js")
R.c("server/chunks/ssr/HRIS-WEB_803df144._.js")
R.c("server/chunks/ssr/[root-of-the-server]__bde7d946._.js")
R.c("server/chunks/ssr/7a46d_bdf05aaa._.js")
R.c("server/chunks/ssr/7a46d_next_dist_84465856._.js")
R.c("server/chunks/ssr/HRIS-WEB_app_6fb00740._.js")
R.c("server/chunks/ssr/7a46d_next_dist_client_components_builtin_global-error_6f1fc40c.js")
R.c("server/chunks/ssr/[root-of-the-server]__947104ad._.js")
R.c("server/chunks/ssr/7a46d_next_dist_client_components_31b1127b._.js")
R.c("server/chunks/ssr/7a46d_next_dist_client_components_builtin_forbidden_19dc40d1.js")
R.c("server/chunks/ssr/7a46d_next_dist_client_components_builtin_unauthorized_1cc0fbc7.js")
R.c("server/chunks/ssr/HRIS-WEB_app_dashboard_layout_tsx_a82e8036._.js")
R.c("server/chunks/ssr/fa1e7_server_app_dashboard_manager-hr_persetujuan-izin-cuti_page_actions_76b742e1.js")
R.m(53243)
module.exports=R.m(53243).exports
