// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/accountant" | "/dashboard/accountant/payroll" | "/dashboard/accountant/payroll/[id]" | "/dashboard/biometrik" | "/dashboard/geofencing" | "/dashboard/login" | "/dashboard/manager-dept" | "/dashboard/manager-dept/jam-kerja" | "/dashboard/manager-dept/karyawan" | "/dashboard/manager-dept/karyawan/edit-pegawai/[id]" | "/dashboard/manager-dept/karyawan/tambah-pegawai" | "/dashboard/manager-dept/laporan" | "/dashboard/manager-dept/lembur" | "/dashboard/manager-dept/lembur/detail/[id]" | "/dashboard/manager-dept/lembur/edit-lembur/[id]" | "/dashboard/manager-dept/lembur/tambah-lembur" | "/dashboard/manager-dept/penugasan" | "/dashboard/manager-dept/penugasan/detail/[id]" | "/dashboard/manager-dept/penugasan/edit-penugasan/[id]" | "/dashboard/manager-dept/penugasan/tambah-penugasan" | "/dashboard/manager-dept/persetujuan-izin-cuti" | "/dashboard/manager-dept/persetujuan-lembur" | "/dashboard/manager-dept/presensi" | "/dashboard/manager-hr" | "/dashboard/manager-hr/departemen" | "/dashboard/manager-hr/departemen/tambah-departemen" | "/dashboard/manager-hr/gaji-karyawan" | "/dashboard/manager-hr/gaji-karyawan/[id]" | "/dashboard/manager-hr/gaji-karyawan/tambah" | "/dashboard/manager-hr/geofencing" | "/dashboard/manager-hr/jabatan" | "/dashboard/manager-hr/jabatan/tambah-jabatan" | "/dashboard/manager-hr/jam-kerja" | "/dashboard/manager-hr/jam-kerja/[id]" | "/dashboard/manager-hr/jam-kerja/tambah-jam-kerja" | "/dashboard/manager-hr/karyawan" | "/dashboard/manager-hr/karyawan/edit-pegawai/[id]" | "/dashboard/manager-hr/karyawan/tambah-pegawai" | "/dashboard/manager-hr/laporan" | "/dashboard/manager-hr/lembur" | "/dashboard/manager-hr/lembur/detail/[id]" | "/dashboard/manager-hr/penugasan" | "/dashboard/manager-hr/persetujuan-izin-cuti" | "/dashboard/manager-hr/persetujuan-lembur" | "/dashboard/manager-hr/persetujuan-registrasi-wajah" | "/dashboard/manager-hr/presensi" | "/dashboard/pegawai" | "/login"
type AppRouteHandlerRoutes = "/api/v1/auth/login" | "/api/v1/auth/refresh" | "/api/v1/logout"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = "/api/v1/[[...path]]" | "/api/v1/auth/[[...path]]" | "/api/v1/leave-requests/[[...path]]" | "/api/v1/logout"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/api/v1/auth/[[...path]]": { "path"?: string[]; }
  "/api/v1/auth/login": {}
  "/api/v1/auth/refresh": {}
  "/api/v1/leave-requests/[[...path]]": { "path"?: string[]; }
  "/api/v1/logout": {}
  "/dashboard": {}
  "/dashboard/accountant": {}
  "/dashboard/accountant/payroll": {}
  "/dashboard/accountant/payroll/[id]": { "id": string; }
  "/dashboard/biometrik": {}
  "/dashboard/geofencing": {}
  "/dashboard/login": {}
  "/dashboard/manager-dept": {}
  "/dashboard/manager-dept/jam-kerja": {}
  "/dashboard/manager-dept/karyawan": {}
  "/dashboard/manager-dept/karyawan/edit-pegawai/[id]": { "id": string; }
  "/dashboard/manager-dept/karyawan/tambah-pegawai": {}
  "/dashboard/manager-dept/laporan": {}
  "/dashboard/manager-dept/lembur": {}
  "/dashboard/manager-dept/lembur/detail/[id]": { "id": string; }
  "/dashboard/manager-dept/lembur/edit-lembur/[id]": { "id": string; }
  "/dashboard/manager-dept/lembur/tambah-lembur": {}
  "/dashboard/manager-dept/penugasan": {}
  "/dashboard/manager-dept/penugasan/detail/[id]": { "id": string; }
  "/dashboard/manager-dept/penugasan/edit-penugasan/[id]": { "id": string; }
  "/dashboard/manager-dept/penugasan/tambah-penugasan": {}
  "/dashboard/manager-dept/persetujuan-izin-cuti": {}
  "/dashboard/manager-dept/persetujuan-lembur": {}
  "/dashboard/manager-dept/presensi": {}
  "/dashboard/manager-hr": {}
  "/dashboard/manager-hr/departemen": {}
  "/dashboard/manager-hr/departemen/tambah-departemen": {}
  "/dashboard/manager-hr/gaji-karyawan": {}
  "/dashboard/manager-hr/gaji-karyawan/[id]": { "id": string; }
  "/dashboard/manager-hr/gaji-karyawan/tambah": {}
  "/dashboard/manager-hr/geofencing": {}
  "/dashboard/manager-hr/jabatan": {}
  "/dashboard/manager-hr/jabatan/tambah-jabatan": {}
  "/dashboard/manager-hr/jam-kerja": {}
  "/dashboard/manager-hr/jam-kerja/[id]": { "id": string; }
  "/dashboard/manager-hr/jam-kerja/tambah-jam-kerja": {}
  "/dashboard/manager-hr/karyawan": {}
  "/dashboard/manager-hr/karyawan/edit-pegawai/[id]": { "id": string; }
  "/dashboard/manager-hr/karyawan/tambah-pegawai": {}
  "/dashboard/manager-hr/laporan": {}
  "/dashboard/manager-hr/lembur": {}
  "/dashboard/manager-hr/lembur/detail/[id]": { "id": string; }
  "/dashboard/manager-hr/penugasan": {}
  "/dashboard/manager-hr/persetujuan-izin-cuti": {}
  "/dashboard/manager-hr/persetujuan-lembur": {}
  "/dashboard/manager-hr/persetujuan-registrasi-wajah": {}
  "/dashboard/manager-hr/presensi": {}
  "/dashboard/pegawai": {}
  "/login": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
