// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/dashboard/accountant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accountant">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accountant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accountant/payroll/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accountant/payroll/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accountant/payroll/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accountant/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accountant/payroll">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accountant/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/biometrik/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/biometrik">> = Specific
  const handler = {} as typeof import("../../app/dashboard/biometrik/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/geofencing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/geofencing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/geofencing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/login">> = Specific
  const handler = {} as typeof import("../../app/dashboard/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/jam-kerja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/jam-kerja">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/jam-kerja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/karyawan/edit-pegawai/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/karyawan/edit-pegawai/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/karyawan/edit-pegawai/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/karyawan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/karyawan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/karyawan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/karyawan/tambah-pegawai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/karyawan/tambah-pegawai">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/karyawan/tambah-pegawai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/laporan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/laporan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/laporan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/lembur/detail/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/lembur/detail/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/lembur/detail/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/lembur/edit-lembur/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/lembur/edit-lembur/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/lembur/edit-lembur/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/lembur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/lembur">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/lembur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/lembur/tambah-lembur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/lembur/tambah-lembur">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/lembur/tambah-lembur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/penugasan/detail/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/penugasan/detail/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/penugasan/detail/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/penugasan/edit-penugasan/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/penugasan/edit-penugasan/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/penugasan/edit-penugasan/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/penugasan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/penugasan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/penugasan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/penugasan/tambah-penugasan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/penugasan/tambah-penugasan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/penugasan/tambah-penugasan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/persetujuan-izin-cuti/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/persetujuan-izin-cuti">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/persetujuan-izin-cuti/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/persetujuan-lembur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/persetujuan-lembur">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/persetujuan-lembur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-dept/presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-dept/presensi">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-dept/presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/departemen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/departemen">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/departemen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/departemen/tambah-departemen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/departemen/tambah-departemen">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/departemen/tambah-departemen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/gaji-karyawan/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/gaji-karyawan/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/gaji-karyawan/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/gaji-karyawan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/gaji-karyawan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/gaji-karyawan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/gaji-karyawan/tambah/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/gaji-karyawan/tambah">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/gaji-karyawan/tambah/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/geofencing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/geofencing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/geofencing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/jabatan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/jabatan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/jabatan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/jabatan/tambah-jabatan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/jabatan/tambah-jabatan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/jabatan/tambah-jabatan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/jam-kerja/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/jam-kerja/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/jam-kerja/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/jam-kerja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/jam-kerja">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/jam-kerja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/jam-kerja/tambah-jam-kerja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/jam-kerja/tambah-jam-kerja">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/jam-kerja/tambah-jam-kerja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/karyawan/edit-pegawai/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/karyawan/edit-pegawai/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/karyawan/edit-pegawai/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/karyawan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/karyawan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/karyawan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/karyawan/tambah-pegawai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/karyawan/tambah-pegawai">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/karyawan/tambah-pegawai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/laporan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/laporan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/laporan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/lembur/detail/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/lembur/detail/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/lembur/detail/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/lembur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/lembur">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/lembur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/penugasan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/penugasan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/penugasan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/persetujuan-izin-cuti/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/persetujuan-izin-cuti">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/persetujuan-izin-cuti/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/persetujuan-lembur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/persetujuan-lembur">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/persetujuan-lembur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/persetujuan-registrasi-wajah/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/persetujuan-registrasi-wajah">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/persetujuan-registrasi-wajah/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/manager-hr/presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manager-hr/presensi">> = Specific
  const handler = {} as typeof import("../../app/dashboard/manager-hr/presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/pegawai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pegawai">> = Specific
  const handler = {} as typeof import("../../app/dashboard/pegawai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/v1/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/v1/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/logout">> = Specific
  const handler = {} as typeof import("../../app/api/v1/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
