import { Employee, Stats } from "@/types";

export const statsData: Stats = {
  totalEmployees: 1240,
  totalEmployeesTrend: 2.4,
  presentToday: 1102,
  presentPercentage: 80,
  lateToday: 12,
  leaveRequests: 8,
  leaveRequestsTrend: -13,
};

export const employeesData: Employee[] = [
  {
    id: "1",
    name: "Fatih Jenkins",
    avatar: "FJ",
    nik: "3174092801920002",
    department: "Pemasaran",
    position: "Creative Lead",
    checkInTime: "08:57 WIB",
    status: "HADIR",
    verified: {
      biometric: true,
      geofencing: true,
    },
  },
  {
    id: "2",
    name: "David Miller",
    avatar: "DM",
    nik: "3174092801920005",
    department: "Teknik",
    position: "Sr. Engineer",
    checkInTime: "09:35 WIB",
    status: "TELAMBAT",
    verified: {
      biometric: true,
      geofencing: true,
    },
    email: "david.miller@company.com",
    phone: "+62 812 3456 7890",
    address: "Jl. Kemang Raya No. 12, Jakarta Selatan",
    joinDate: "12 Januari 2021",
    employmentStatus: "Pegawai Tetap",
    workYears: 4,
  },
  {
    id: "3",
    name: "Alex Wong",
    avatar: "AW",
    nik: "3174092801920009",
    department: "Desain",
    position: "UI Designer",
    checkInTime: "08:42 WIB",
    status: "HADIR",
    verified: {
      biometric: true,
      geofencing: true,
    },
  },
  {
    id: "4",
    name: "Sarah Jenkins",
    avatar: "SJ",
    nik: "3174092801920002",
    department: "Pemasaran",
    position: "Creative Lead",
    status: "AKTIF",
  },
];

// Expanded employee list untuk halaman pegawai
export const allEmployeesData: Employee[] = [
  {
    id: "1",
    name: "Sarah Jenkins",
    avatar: "SJ",
    nik: "3174092801920002",
    department: "Pemasaran",
    position: "Creative Lead",
    status: "AKTIF",
    email: "sarah.jenkins@company.com",
    phone: "+62 811 2345 6789",
    address: "Jl. Sudirman No. 45, Jakarta Pusat",
    joinDate: "15 Maret 2020",
    employmentStatus: "Pegawai Tetap",
    workYears: 5,
  },
  {
    id: "2",
    name: "David Miller",
    avatar: "DM",
    nik: "3174092801920005",
    department: "Teknik",
    position: "Sr. Engineer",
    status: "AKTIF",
    email: "david.miller@company.com",
    phone: "+62 812 3456 7890",
    address: "Jl. Kemang Raya No. 12, Jakarta Selatan",
    joinDate: "12 Januari 2021",
    employmentStatus: "Pegawai Tetap",
    workYears: 4,
  },
  {
    id: "3",
    name: "Alex Wong",
    avatar: "AW",
    nik: "3174092801920009",
    department: "Desain",
    position: "UI Designer",
    status: "NONAKTIF",
    email: "alex.wong@company.com",
    phone: "+62 813 4567 8901",
    address: "Jl. Gatot Subroto No. 88, Jakarta Selatan",
    joinDate: "20 Juni 2019",
    employmentStatus: "Kontrak",
    workYears: 3,
  },
];

export const navigationItems = [
  { name: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { name: "Pegawai", href: "/dashboard/pegawai", icon: "Users" },
  { name: "Biometrik", href: "/dashboard/biometrik", icon: "Fingerprint" },
  { name: "Geofencing", href: "/dashboard/geofencing", icon: "MapPin" },
  { name: "Presensi", href: "/dashboard/presensi", icon: "ClipboardCheck" },
  { name: "Jam Kerja", href: "/dashboard/jam-kerja", icon: "Clock" },
  { name: "Keamanan", href: "/dashboard/keamanan", icon: "Shield" },
  { name: "Audit Log", href: "/dashboard/audit-log", icon: "FileText" },
  { name: "Notifikasi", href: "/dashboard/notifikasi", icon: "Bell" },
];